### ISSUE TITLE
something about the attention

### ISSUE THREAD

**Issue by ryanbbd** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#13]
Hi, I find that you upload new code. In GlobalAttention and GlobalAttentionPatch, you use point-wise product and matrix product separately. Could you tell me the differences between them? why choose two different actions?

**Comment by ryanbbd** [comment]
And, sorry to bother again, in your code, the one value of mask means a hole pixel, but in the paper, the zero value means a hole pixel, is it?

**Comment by SayedNadim** [comment]
Hi,
Sorry for the late reply. Patches are 3x3 in spatial size. So, using self-attention is not going to give any useful information. However, if we calculate the channel-wise information, we can use the information as background contribution. That's why we use different matrix multiplication.
And for the paper and code definition, I reckon it's a typo in the paper. 
Thanks for the questions.
Cheers!

**Comment by SayedNadim** [comment]
Closing issue as no further activities are reported.
